name: Build
on: [push]
jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build APK
        uses: s0/buildozer-action@v1
        with:
          buildozer_version: master
          command: buildozer android debug
